version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - app_network

  web:
    build: .
    command: sh -c "python manage.py wait_for_db && python manage.py migrate --noinput && gunicorn lcdh_app.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/lcdhsite/static
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app_network

  nginx:
    image: nginx:1.21
    volumes:
      - static_volume:/app/lcdhsite/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app_network

volumes:
  postgres_data:
  static_volume:

networks:
  app_network:
    driver: bridge